set(groot, 'defaultaxeslinewidth', 3, ...
    'defaultlinelinewidth', 3, ...
    'defaultstemlinewidth', 2, ...
    'defaultstemmarkersize', 10, ...,
    'defaultstemmarkerfacecolor', 'auto', ...
    'defaultaxesygrid', 'on', ...
    'defaultaxesyminorgrid', 'on', ...
    'defaultfigureposition', [99 560 783 400], ...
    'defaultaxesfontsize', 26, ...
    'defaultaxesyminortick', 'on', ...
    'defaultaxestickdir', 'out', ...
    'defaultAxesTickDirMode', 'manual', ...
    'defaultaxesticklength', 6*[0.001 0.001], ...
    'defaulttextfontname', 'CMU Serif', ...
    'defaultaxesfontname', 'CMU Serif', ...
    'defaulttextinterpreter','latex', ...
    'defaultAxesTickLabelInterpreter','latex', ...
    'defaultLegendInterpreter','latex', ...  
    'defaultfigurecolor', 'white' ...
    );
